[2023-10-14T05:14:56.668+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: titanic.read_db scheduled__2023-10-14T05:12:00+00:00 [queued]>
[2023-10-14T05:14:56.675+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: titanic.read_db scheduled__2023-10-14T05:12:00+00:00 [queued]>
[2023-10-14T05:14:56.675+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-10-14T05:14:56.688+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): read_db> on 2023-10-14 05:12:00+00:00
[2023-10-14T05:14:56.692+0000] {standard_task_runner.py:57} INFO - Started process 3085 to run task
[2023-10-14T05:14:56.695+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'titanic', 'read_db', 'scheduled__2023-10-14T05:12:00+00:00', '--job-id', '443', '--raw', '--subdir', 'DAGS_FOLDER/titanic01.py', '--cfg-path', '/tmp/tmp5s1q__bv']
[2023-10-14T05:14:56.697+0000] {standard_task_runner.py:85} INFO - Job 443: Subtask read_db
[2023-10-14T05:14:56.734+0000] {task_command.py:415} INFO - Running <TaskInstance: titanic.read_db scheduled__2023-10-14T05:12:00+00:00 [running]> on host 89ffa62682cc
[2023-10-14T05:14:56.894+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='titanic' AIRFLOW_CTX_TASK_ID='read_db' AIRFLOW_CTX_EXECUTION_DATE='2023-10-14T05:12:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-14T05:12:00+00:00'
[2023-10-14T05:14:56.909+0000] {base.py:73} INFO - Using connection ID 'mydb' for task execution.
[2023-10-14T05:14:57.352+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-14T05:14:57.361+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=titanic, task_id=read_db, execution_date=20231014T051200, start_date=20231014T051456, end_date=20231014T051457
[2023-10-14T05:14:57.429+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-14T05:14:57.444+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
