[2023-10-14T05:17:01.983+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: titanic.read_db scheduled__2023-10-14T05:16:00+00:00 [queued]>
[2023-10-14T05:17:01.991+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: titanic.read_db scheduled__2023-10-14T05:16:00+00:00 [queued]>
[2023-10-14T05:17:01.991+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-14T05:17:02.003+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): read_db> on 2023-10-14 05:16:00+00:00
[2023-10-14T05:17:02.008+0000] {standard_task_runner.py:57} INFO - Started process 3158 to run task
[2023-10-14T05:17:02.010+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'titanic', 'read_db', 'scheduled__2023-10-14T05:16:00+00:00', '--job-id', '453', '--raw', '--subdir', 'DAGS_FOLDER/titanic01.py', '--cfg-path', '/tmp/tmpdm1e45ma']
[2023-10-14T05:17:02.013+0000] {standard_task_runner.py:85} INFO - Job 453: Subtask read_db
[2023-10-14T05:17:02.056+0000] {task_command.py:415} INFO - Running <TaskInstance: titanic.read_db scheduled__2023-10-14T05:16:00+00:00 [running]> on host 89ffa62682cc
[2023-10-14T05:17:02.278+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='titanic' AIRFLOW_CTX_TASK_ID='read_db' AIRFLOW_CTX_EXECUTION_DATE='2023-10-14T05:16:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-14T05:16:00+00:00'
[2023-10-14T05:17:02.307+0000] {base.py:73} INFO - Using connection ID 'mydb' for task execution.
[2023-10-14T05:17:02.970+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-14T05:17:02.977+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=titanic, task_id=read_db, execution_date=20231014T051600, start_date=20231014T051701, end_date=20231014T051702
[2023-10-14T05:17:03.025+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-14T05:17:03.037+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
